In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
import numpy as np
import math

Settings

In [3]:
BASE_PATH = '/content/drive/MyDrive/Facultate/year2-sem2/data-vis/project'

In [4]:
df = pd.read_csv(f'{BASE_PATH}/data/housing.csv')
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,13 Burns St,4,h,1480000.0,PI,Jas,24/02/2018,6.3,3013.0,...,1.0,3.0,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0
34853,Yarraville,29A Murray St,2,h,888000.0,SP,Sweeney,24/02/2018,6.3,3013.0,...,2.0,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0
34854,Yarraville,147A Severn St,2,t,705000.0,S,Jas,24/02/2018,6.3,3013.0,...,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
34855,Yarraville,12/37 Stephen St,3,h,1140000.0,SP,hockingstuart,24/02/2018,6.3,3013.0,...,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0
34856,Yarraville,3 Tarrengower St,2,h,1020000.0,PI,RW,24/02/2018,6.3,3013.0,...,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34857 non-null  object
 1   Address        34857 non-null  object
 2   Rooms          34857 non-null  int64
 3   Type           34857 non-null  object
 4   Price          27247 non-null  float64
 5   Method         34857 non-null  object
 6   SellerG        34857 non-null  object
 7   Date           34857 non-null  object
 8   Distance       34856 non-null  float64
 9   Postcode       34856 non-null  float64
 10  Bedroom2       26640 non-null  float64
 11  Bathroom       26631 non-null  float64
 12  Car            26129 non-null  float64
 13  Landsize       23047 non-null  float64
 14  BuildingArea   13742 non-null  float64
 15  YearBuilt      15551 non-null  float64
 16  CouncilArea    34854 non-null  object
 17  Lattitude      26881 non-null  float64
 18  Longtitude     26881 non-null  float64
 19  Regionname     34854 non-null  object
 20  Propertycount  34854 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 5.6+ MB

In [6]:
df.isna().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
YearBuilt        19306
CouncilArea          3
Lattitude         7976
Longtitude        7976
Regionname           3
Propertycount        3
dtype: int64

In [7]:
df.dropna(subset = ['Price'], inplace=True)
df.reset_index(drop=True, inplace=True)
df.isna().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price                0
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          6441
Bathroom          6447
Car               6824
Landsize          9265
BuildingArea     16591
YearBuilt        15163
CouncilArea          3
Lattitude         6254
Longtitude        6254
Regionname           3
Propertycount        3
dtype: int64

In [8]:
# Distance - can be somewhat guessed by suburb
for idx, row in df.iterrows():
  if math.isnan(row['Distance']):
    first_match = df[df.Suburb == row.Suburb].iloc[0]
    df.loc[idx, 'Distance'] = first_match.Distance

In [9]:
# Postcode - can be somewhat guessed by suburb
for idx, row in df.iterrows():
  if math.isnan(row['Postcode']):
    first_match = df[df.Suburb == row.Suburb].iloc[0]
    df.loc[idx, 'Postcode'] = first_match.Postcode

In [10]:
# Bedroom - could probably infer from area but has too many missing values
df['Bedroom2'].fillna(value=round(df['Bedroom2'].mean()), inplace=True)

In [11]:
# Bathroom - could probably infer from area but has too many missing values
df['Bathroom'].fillna(value=round(df['Bathroom'].mean()), inplace=True)

In [12]:
# Car slots - infer from nearest value with same "Type" and "Rooms" count
for idx, row in df.iterrows():
  if math.isnan(row['Car']):
    first_match = df[(df.Rooms == row.Rooms) & (df.Type == row.Type)].iloc[0]
    if math.isnan(first_match.Car):
      df.loc[idx, 'Car'] = round(df['Car'].mean())
    else:
      df.loc[idx, 'Car'] = first_match.Car

In [13]:
# Landsize - infer from nearest value with same Type and Rooms count
for idx, row in df.iterrows():
  if math.isnan(row['Landsize']):
    first_match = df[(df.Rooms == row.Rooms) & (df.Type == row.Type)].iloc[0]
    if math.isnan(first_match.Landsize):
      df.loc[idx, 'Landsize'] = round(df['Landsize'].mean())
    else:
      df.loc[idx, 'Landsize'] = first_match.Landsize

In [14]:
# BuildingArea - infer from nearest value with same Type and Rooms count
for idx, row in df.iterrows():
  if math.isnan(row['BuildingArea']):
    first_match = df[(df.Rooms == row.Rooms) & (df.Type == row.Type)].iloc[0]
    if math.isnan(first_match.BuildingArea):
      df.loc[idx, 'BuildingArea'] = round(df['BuildingArea'].mean())
    else:
      df.loc[idx, 'BuildingArea'] = first_match.BuildingArea

In [15]:
# YearBuilt - no way to infer
df['YearBuilt'].fillna(value=round(df['YearBuilt'].mean()), inplace=True)

In [16]:
# Council area - high chance to overlap with suburb
for idx, row in df.iterrows():
  if pd.isnull(row['CouncilArea']):
    first_match = df[df.Suburb == row.Suburb].iloc[0]
    df.loc[idx, 'CouncilArea'] = first_match.CouncilArea

In [17]:
# Latitude - mean of other latitudes inside same suburb or region
for idx, row in df.iterrows():
  if math.isnan(row['Lattitude']):
    suburb_lat_mean = df[df.Suburb == row.Suburb]['Lattitude'].mean()
    if math.isnan(suburb_lat_mean):
      df.loc[idx, 'Lattitude'] = df[df.Regionname == row.Regionname]['Lattitude'].mean()
    else:
      df.loc[idx, 'Lattitude'] = suburb_lat_mean

In [18]:
# Longitude - mean of other longitudes inside same suburb or region
for idx, row in df.iterrows():
  if math.isnan(row['Longtitude']):
    suburb_lat_mean = df[df.Suburb == row.Suburb]['Longtitude'].mean()
    if math.isnan(suburb_lat_mean):
      df.loc[idx, 'Longtitude'] = df[df.Regionname == row.Regionname]['Longtitude'].mean()
    else:
      df.loc[idx, 'Longtitude'] = suburb_lat_mean

In [19]:
# Regionname - can be inferred from suburb
for idx, row in df.iterrows():
  if pd.isnull(row['Regionname']):
    first_match = df[df.Suburb == row.Suburb].iloc[0]
    df.loc[idx, 'Regionname'] = first_match.Regionname

In [20]:
# Propertcount - can be inferred from suburb
for idx, row in df.iterrows():
  if pd.isnull(row['Propertycount']):
    first_match = df[df.Suburb == row.Suburb].iloc[0]
    df.loc[idx, 'Propertycount'] = first_match.Propertycount

In [21]:
df.isna().sum()

Suburb           0
Address          0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Date             0
Distance         0
Postcode         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
YearBuilt        0
CouncilArea      0
Lattitude        0
Longtitude       0
Regionname       0
Propertycount    0
dtype: int64

In [22]:
df.to_csv('cleaned_housing.csv', header=True, index=False)